### PR TITLE
fix: replace omptempty by omitempty in struct tag fields and fix some typos

### PR DESCRIPTION
**Pull request by dragonis41**
* Fix mistyping as stated in issue #53 
* Fix function name in the comments for auto-documentation

If someone with a working Odoo and code can check if I haven't broken anything before merging, it will be appreciated :)

### CODE REVIEW

**Comment by ahuret** [comment]
cc @Stolexiy (if you can check it doesn't break anything) :-)

**Comment by dragonis41** [comment]
Wait I just saw a bug, I'll fix it ^^

**Comment by dragonis41** [comment]
I was thinking that my regex had put an extra "s" in the name of functions ending with an "s" but no, it was already here.
Have I missed something or is this a typo in the function name ? ^^ 
https://github.com/skilld-labs/go-odoo/blob/65da36bbbdb134d922044b0b7de638b3d7f15b4e/res_users.go#L183C18-L183C33

**Comment by ahuret** [comment]
> I was thinking that my regex had put an extra "s" in the name of functions ending with an "s" but no, it was already here. Have I missed something or is this a typo in the function name ? ^^ https://github.com/skilld-labs/go-odoo/blob/65da36bbbdb134d922044b0b7de638b3d7f15b4e/res_users.go#L183C18-L183C33

No worries, the Odoo model name is indeed `res.users` and not `res.user`. As the code is auto-generated, the extra "S" is added to signify it's plural. Though it might seem odd in the context of res.users, it's actually the intended behavior :-)

**Comment by Stolexiy** [comment]
> cc @Stolexiy (if you can check it doesn't break anything) :-) otherwise LGTM ! Thanks a lot @dragonis41 !!

No issues found, my code works as before. LGTM! Thanks, @dragonis41

**Comment by dragonis41** [comment]
You're welcome :)

**Pull request merged**
